apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: auto-scale-nginx
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: nginx-nginx
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 11