apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  rules:
  - host: nginx.kub
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx-nginx
          servicePort: 80