apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nginx
  labels:
    type: local
spec:
  storageClassName: pv-nginx
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  # nfs:
  #   server: 192.168.1.179
  #   path: "/mnt/data/www"
  hostPath:
    path: "/mnt/www"