apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # --> Nom de l'antité
  name: pvc-nginx
spec:
  # --> Connexion à l'entitée "pv-nginx" voir: pv.yml
  storageClassName: pv-nginx
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi