apiVersion: v1
kind: Service
metadata:
  name: nginx-nginx
  labels:
    app: nginx-nginx
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    app: nginx
